In [ ]:
import numpy as np

M1 = np.array([[1,2,3], [4,5,6],[7,8,9]])
M2 = M1.transpose()
M3 = M1.dot(M2)  
print(M3)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [ ]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd
# define a matrix
M1 = array([[1,2,3], [4,5,6],[7,8,9]])
M2 = M1.transpose()
M3 = M1.dot(M2)  

print(M3)
# Singular-value decomposition
U, s, VT = svd(M3)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
[[ 14.  32.  50.]
 [ 32.  77. 122.]
 [ 50. 122. 194.]]


In [ ]:
array_2d_sqrt = np.sqrt(Sigma)
y = np.linalg.inv(array_2d_sqrt) 
print(y)

[[5.93538619e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.36005742e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.61494565e+07]]


In [ ]:
UT=U.transpose()
c=y.dot(UT.dot(M1))
print(c)

[[-4.79671178e-01 -5.72367794e-01 -6.65064410e-01]
 [-7.76690990e-01 -7.56864701e-02  6.25318050e-01]
 [ 9.29015319e-08  2.32253830e-08 -3.48380745e-08]]


In [ ]:
CT = c.transpose()
CCT = c.dot(CT)  
print(CCT)

[[ 1.00000000e+00 -1.79450563e-15 -3.46860850e-08]
 [-1.79450563e-15  1.00000000e+00 -9.56985069e-08]
 [-3.46860850e-08 -9.56985069e-08  1.03838045e-14]]


$$\begin{bmatrix} X_1{(t)} \\ X_2{(t)}\end{bmatrix}=\begin{bmatrix} a_{11}& a_{12}\\ a_{21}& a_{22}\end{bmatrix}\begin{bmatrix} S_1{(t)} \\ S_2{(t)}\end{bmatrix}$$

$$\begin{bmatrix} S_1{(t)} \\ S_2{(t)}\end{bmatrix}=\begin{bmatrix} W_1{(t)} \\ W_2{(t)}\end{bmatrix}\begin{bmatrix} X_1{(t)} \\ X_2{(t)}\end{bmatrix}$$

$$\begin{bmatrix} W_1{(t)} \\ W_2{(t)}\end{bmatrix}=\begin{bmatrix} Degauss_1{(t)} \\ Degauss_2{(t)}\end{bmatrix}\begin{bmatrix} Decorrelate_1{(t)} \\ Decorrelate_2{(t)}\end{bmatrix}$$

$$\begin{bmatrix} S_1{(t)} \\ S_2{(t)}\end{bmatrix}=\begin{bmatrix} Degauss_1{(t)} \\ Degauss_2{(t)}\end{bmatrix}\begin{bmatrix} Decorrelate_1{(t)} \\ Decorrelate_2{(t)}\end{bmatrix}\begin{bmatrix} X_1{(t)} \\ X_2{(t)}\end{bmatrix}$$