In [4]:
import pandas as pd
from google.colab import files


uploaded = files.upload()


Saving WIREpulllength.csv to WIREpulllength.csv


In [5]:
import io

data = pd.read_csv(io.BytesIO(uploaded['WIREpulllength.csv']))
data.head()


WIRELENGTH  DIEHEIGHT  PULLSTRENGTH
0           2         50          9.95
1           8        110         24.45
2          11        120          1.75
3          10        550         35.00
4           8        295         25.02

In [6]:
import numpy as np
WIRELENGTH=data.WIRELENGTH.values
DIEHEIGHT=data.DIEHEIGHT.values
#print(DIEHEIGHT)
PULLSTRENGTH=data.PULLSTRENGTH.values
X_mat=np.vstack((np.ones(len(WIRELENGTH)), WIRELENGTH,DIEHEIGHT)).T
print(X_mat)
Y_mat=np.vstack((PULLSTRENGTH))
print(Y_mat)

[[  1.   2.  50.]
 [  1.   8. 110.]
 [  1.  11. 120.]
 [  1.  10. 550.]
 [  1.   8. 295.]
 [  1.   4. 200.]
 [  1.   2. 375.]
 [  1.   2.  52.]
 [  1.   9. 100.]
 [  1.   8. 300.]
 [  1.   4. 412.]
 [  1.  11. 400.]
 [  1.  12. 500.]
 [  1.   2. 360.]
 [  1.   4. 205.]
 [  1.   4. 400.]
 [  1.  20. 600.]
 [  1.   1. 585.]
 [  1.  10. 540.]
 [  1.  15. 250.]
 [  1.  15. 290.]
 [  1.  16. 510.]
 [  1.  17. 590.]
 [  1.   6. 100.]
 [  1.   5. 400.]]
[[ 9.95]
 [24.45]
 [ 1.75]
 [35.  ]
 [25.02]
 [16.86]
 [14.38]
 [ 9.6 ]
 [24.35]
 [27.5 ]
 [17.08]
 [37.  ]
 [41.95]
 [11.66]
 [21.65]
 [17.89]
 [69.  ]
 [10.3 ]
 [34.93]
 [46.59]
 [44.88]
 [54.12]
 [56.63]
 [22.13]
 [21.15]]


In [7]:
weights=(np.linalg.inv(X_mat.T.dot(X_mat))).dot(X_mat.T).dot(Y_mat)
print(weights)

[[-0.47838466]
 [ 2.48574937]
 [ 0.02359721]]


In [8]:
XTX=X_mat.T.dot(X_mat)

print(XTX)

[[2.500000e+01 2.060000e+02 8.294000e+03]
 [2.060000e+02 2.396000e+03 7.717700e+04]
 [8.294000e+03 7.717700e+04 3.531848e+06]]


In [9]:
XTXI=np.linalg.inv(X_mat.T.dot(X_mat))
print(XTXI)

[[ 2.14652617e-01 -7.49091422e-03 -3.40389087e-04]
 [-7.49091422e-03  1.67076313e-03 -1.89178140e-05]
 [-3.40389087e-04 -1.89178140e-05  1.49587616e-06]]


In [11]:
XTY=X_mat.T.dot(Y_mat)
print(XTY)

[[   695.82]
 [  7678.47]
 [271216.71]]


In [ ]:
(np.linalg.inv(X_mat.T.dot(X_mat))).dot(X_mat.T).dot(Y_mat)

In [ ]:
result=X_mat.dot(weights)
print(result)

In [ ]:
print(Y_mat-result)