#  Discrete Features

## 1.Training data

There are six sports documents

there are five news documents

## 2.Create Vocabulary(bag of words)

From the **training data create vocabulary array** consisting of unique words common to sports and news documents

(while creating vocabulary donot consider words like :a,an,the,is...etc)

$ V=
\begin{bmatrix}
 defence,drink,field,goal,performance,speed,tutor,variance\\ 
  \end{bmatrix}$

Mathematically we can write as:

$ V=
\begin{bmatrix}
 x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8\\ 
  \end{bmatrix}$


## 3. Represent vocabulary elements in the six sports documents as an  array

$ C^{sports}=
\begin{bmatrix}
 1&0&0&0&1&1&1&1\\ 
 0&0&1&0&1&1&0&0\\
 0&1&0&1&0&1&1&0\\ 
 1&0&0&1&0&1&0&1\\
 1&0&0&0&1&0&1&1\\ 
 0&0&1&1&0&0&1&1\\
 \end{bmatrix}$

 Here each row represents vocabulary present in one sports document 

 **Explanation for first row:**

 Vocabulary is:

 $       V=
\begin{bmatrix}
 defence,drink,field,goal,performance,speed,tutor,variance\\ 
  \end{bmatrix}$

$ C^{sports}[0]=
\begin{bmatrix}
 1&0&0&0&1&1&1&1\\ 
  \end{bmatrix}$

  first sports document has unique words :
  **defence,perormance,speed,tutor,variance**

  identify unique words in sixth sports document____________



## 4.Represent vocabulary elements in the Five News documents as an  array

$ C^{news}=
\begin{bmatrix}
 0&1&1&0&0&0&1&0\\ 
 1&1&0&1&0&0&1&1\\
 0&1&1&0&0&1&0&0\\ 
 0&0&0&0&0&0&0&0\\
 0&0&1&0&1&0&1&0\\ 
  \end{bmatrix}$

 Here each row represents unique vocabulary present in one news document 

 **Explanation for first row:**

 Vocabulary is:

 $       V=
\begin{bmatrix}
 defence,drink,field,goal,performance,speed,tutor,variance\\ 
  \end{bmatrix}$

$ C^{news}[0]=
\begin{bmatrix}
 0&1&1&0&0&0&1&0\\ 
  \end{bmatrix}$

  first news document has unique words :
  **drink,field,tutor**

  identify unique words in second news document____________



## 5.Test Data
 given following two documents we have to classify them into sports or news documents Using naive bayes classifier

$ x_j=
\begin{bmatrix}
 x_1&x_2&x_3&x_4&x_5&x_6&x_7&x_8\\ 
  \end{bmatrix}$

$ X_1=
\begin{bmatrix}
 1 \ & \ 0 \ & \ 0 \ & \ 1 \ & \ 1 \ &  \ 1 \ & \ 0 \ & \ 1\\ 
  \end{bmatrix}$

$ X_2=
\begin{bmatrix}
 0 \ & \ 1 \ & \ 1 \ & \ 0 \ & \ 1 \ & \ 0 \ & \ 1 \ & \ 0\\ 
  \end{bmatrix}$


## 6.what are words present in $X_1$ and $ X_2$?_______________

## 7.Discriminant Function

Naive bayes classifier Estimate :

$P(C_{sports}/X_1)=P(X_1/D_{sports})P(D_{sports})$

Use bernoulli distribution

$P(X_1/D_{sports})=$ product of probabilities of words in $X_1$ Document

$P(X_1/D_{sports})=∏^d_{j=1}P^{x_j}_{(sports)j} {(1-P_{(sports)j})}^(1-{x_j})$


 Here $x_j$ represents $word_j i.e.,(word_1 to word_8 )$  in $X_1$ document

 Here $x_j$ is a random bernouli variable with value =1 if word is present in $X_1$ document  or 0 if absent

Here $P_{(sports)j}$ is probability of $word_j$ in sports document

$logP(X_1/D_{sports})=Σ^d_{j=1}[{x_j}P_{(sports)j} +(1-x_j){(1-P_{(sports)j})}]$ ...(1)


The discriminant function is :


$g_{sports}(X_1) = log P(X_1|C_{sports}) + log P(C_{sports})$

substitute ..(1) in above equation

$g_{sports}(X_1) = Σ^d_{j=1}[{x_j}P_{(sports)j} +(1-x_j){(1-P_{(sports)j})}] + log P(C_{sports})$

General discriminant equation is:
$g_i(X_1) = Σ^d_{j=1}[{x_j}P_{ij} +(1-x_j){(1-P_{ij})}] + log P(C_{sports})$

Here $P(C_{sports})$ is calculated from training data

Here $P_{ij}=P_{(sports)j}$ is calculated from training data

Here $x_j$ is calculated from test data=1 or 0


## 8.how to find priors and likelihoods?

**priors**

$P(C_{sports})=\frac{No \ of \ sports \ documents \ in \ training data}{Total \ documents \  in \ training data}$

$P(C_{sports})=\frac{6}{11}$

$P(C_{news})=\frac{5}{11}$

***likelihoods**

$P_{ij}=P_{(sports)j} =\frac{Total\ word_j 's \ in Sports\ Documents}{Total \ Sports \ documents}$

$P_{i1}=P_{(sports)1}=\frac{3}{6}$

$P_{i2}=P_{(sports)2}=\frac{1}{6}$

$P_{i3}=P_{(sports)3}=\frac{2}{6}$

$P_{i4}=P_{(sports)4}=\frac{3}{6}$

$P_{i5}=P_{(sports)5}=\frac{3}{6}$

$P_{i6}=P_{(sports)6}=\frac{4}{6}$

$P_{i7}=P_{(sports)7}=\frac{4}{6}$

$P_{i8}=P_{(sports)8}=\frac{4}{6}$

$P_{i1}=P_{(news)1}=\frac{1}{5}$

$P_{i2}=P_{(news)2}=\frac{3}{5}$

$P_{i3}=P_{(news)3}=\frac{3}{5}$

$P_{i4}=P_{(news)4}=\frac{1}{5}$

$P_{i5}=P_{(news)5}=\frac{1}{5}$

$P_{i6}=P_{(news)6}=\frac{1}{5}$

$P_{i7}=P_{(news)7}=\frac{3}{5}$

$P_{i8}=P_{(news)8}=\frac{1}{5}$


**Here $x_j$ for test documents**

$ x_j=
\begin{bmatrix}
 x_1&x_2&x_3&x_4&x_5&x_6&x_7&x_8\\ 
  \end{bmatrix}$

$ X_1=
\begin{bmatrix}
 1 \ & \ 0 \ & \ 0 \ & \ 1 \ & \ 1 \ &  \ 1 \ & \ 0 \ & \ 1\\ 
  \end{bmatrix}$

$ X_2=
\begin{bmatrix}
 0 \ & \ 1 \ & \ 1 \ & \ 0 \ & \ 1 \ & \ 0 \ & \ 1 \ & \ 0\\ 
  \end{bmatrix}$



## 9.Calculate values and classify  $X_1$ and $X_2$ as sports or news documents

In [ ]:
import warnings
warnings.filterwarnings('ignore')


In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
 
vectorizer = CountVectorizer()


In [ ]:
# Create sample set of documents
#
docs = np.array(['Mirabai has won a silver medal in weight lifting in Tokyo olympics 2021',
                 'Sindhu has won a bronze medal in badminton in Tokyo olympics',
                 'Indian hockey team is in top four team in Tokyo olympics 2021 after 40 years'])
#
# Fit the bag-of-words model
#
bag = vectorizer.fit_transform(docs)
#

In [ ]:
# Get unique words / tokens found in all the documents. The unique words / tokens represents
# the features
#
print(vectorizer.get_feature_names())
#


['2021', '40', 'after', 'badminton', 'bronze', 'four', 'has', 'hockey', 'in', 'indian', 'is', 'lifting', 'medal', 'mirabai', 'olympics', 'silver', 'sindhu', 'team', 'tokyo', 'top', 'weight', 'won', 'years']


In [ ]:
# Associate the indices with each unique word
#
print(vectorizer.vocabulary_)
#


{'mirabai': 13, 'has': 6, 'won': 21, 'silver': 15, 'medal': 12, 'in': 8, 'weight': 20, 'lifting': 11, 'tokyo': 18, 'olympics': 14, '2021': 0, 'sindhu': 16, 'bronze': 4, 'badminton': 3, 'indian': 9, 'hockey': 7, 'team': 17, 'is': 10, 'top': 19, 'four': 5, 'after': 2, '40': 1, 'years': 22}


In [ ]:
# Print the numerical feature vector
#
print(bag.toarray())

[[1 0 0 0 0 0 1 0 2 0 0 1 1 1 1 1 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 1 0 2 0 0 0 1 0 1 0 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 1 2 1 1 0 0 0 1 0 0 2 1 1 0 0 1]]
