##  Multivariate Data


### 1.How to represent Machine Learning Input data in Matrix?

\begin{equation*}
X=\begin{vmatrix}
\mathbf{X^1_1} & \mathbf{X^1_2} &.. &\mathbf{X^1_d} \\
\mathbf{X^2_1} & \mathbf{X^2_2} &.. &\mathbf{X^2_d} \\
\vdots\\
\mathbf{X^N_1} & \mathbf{X^N_2} &.. &\mathbf{X^N_d} \\
\end{vmatrix}  
\end{equation*}

## 2. what is d in above Matrix?


#### d=variables(inputs/features/attributes)


## 3.what is N in above Matrix?

#### N=events
#### N rows=observations or instances or examples 

## 4.what is covariance and correlation in multivariate(bivariate) distribution?

### For population
$\boldsymbol{COV(X_i,X_j)=σ_{ij}=\frac{\sum(x_i-\bar{x_i})(x_j-\bar{x_j})}{N}}$

### For sample
$\boldsymbol{COV(X_i,X_j)=σ_{ij}=\frac{\sum(x_i-\bar{x_i})(x_j-\bar{x_j})}{N-1}}$

$\boldsymbol{COrr(X_i , X_j)=\frac{COV(X_i,X_j)}{\sqrt{\sigma^2_{x_i}\sigma^2_{X_j}}}}$= pearson correlation coefficient

$\boldsymbol{COrr(X_i , X_j)=\frac{COV(X_i,X_j)}{\sigma_{x_i}\sigma_{X_j}}}$= pearson correlation coefficient





## EXAMPLE For calculation of Covariation and Correlation 

### $X_i$ 2  8 18 20 28 30

### $x_j$ 5 12 18 23 45 50

### Number of observations = 6

### Mean of $X_i$ = 17.67

### Mean of $x_j$ = 25.5




### variance of $X_i =σ^2_i= \frac{[(2−17.67)^2+(8−17.67)^2+(18−17.67)^2+(20−17.67)^2+(28−17.67)^2+(30−17.67)^2] }{5} = 120.66$

### variance of $x_j =σ^2_j= \frac{[(5−25.5)^2+(12−25.5)^2+(18−25.5)^2+(23−25.5)^2+(45−25.5)^2+(50−25.5)^2] }{5}= 329.1$




$Cov(X_i,X_j)=\frac{(2 – 17.67)(5 – 25.5) + (8 – 17.67)(12 – 25.5) + (18 – 17.67)(18 – 25.5) + (20 – 17.67)(23 – 25.5) + (28 – 17.67)(45 – 25.5) + (30 – 17.67)(50 – 25.5)}{5} =189.4$




$Corr(X_i,X_j)=\frac{189.4}{\sqrt{120.66} * \sqrt{329.1}} =0.95$

## 5.What is pearson correlation coefficient?

$\boldsymbol\rho_{x_i x_j}=\frac{Cov(X_i,X_j)}{\sigma_{x_i} \sigma_{x_j}}$

We use following formula frequently

$\boldsymbol Cov(X_i,X_j)=\boldsymbol\rho_{x_i x_j}*{\sigma_{x_i} \sigma_{x_j}}$


## 6. How to represent Covariance matrix

### Covariance matrix for Bivariate normal distribution

\begin{equation*}
Σ=\begin{vmatrix}
\mathbf{\sigma^2_i} & \mathbf{\sigma_{12}} \\
\mathbf{\sigma_{12}} & \mathbf{\sigma^2_j} \\
\end{vmatrix}  
\end{equation*}

### frequently used Covariance matrix for Bivariate normal distribution

\begin{equation*}
Σ=\begin{vmatrix}
\mathbf{\sigma^2_i} & \mathbf{ρ*\sigma_1\sigma_2} \\
\mathbf{ρ*\sigma_1\sigma_2} & \mathbf{\sigma^2_j} \\
\end{vmatrix}  
\end{equation*}

## Covariance matrix for Multivariate normal distribution

\begin{equation*}
Σ=\begin{vmatrix}
\mathbf{\sigma^2_1} & \mathbf{\sigma_{12}} & \mathbf{\sigma_{13}} & \mathbf{\sigma_{14}}& \mathbf{\sigma_{15}} \\
\mathbf{\sigma_{12}} & \mathbf{\sigma^2_2} & \mathbf{\sigma_{23}} & \mathbf{\sigma_{24}}& \mathbf{\sigma_{25}} \\
\mathbf{\sigma_{31}} & \mathbf{\sigma_{32}} & \mathbf{\sigma^2_3} & \mathbf{\sigma_{34}}& \mathbf{\sigma_{35}} \\
\mathbf{\sigma_{41}} & \mathbf{\sigma_{42}} & \mathbf{\sigma_{43}} & \mathbf{\sigma^2_4}& \mathbf{\sigma_{45}} \\
\mathbf{\sigma_{51}} & \mathbf{\sigma_{52}} & \mathbf{\sigma_{53}} & \mathbf{\sigma_{54}}& \mathbf{\sigma^2_5} \\
\end{vmatrix}  
\end{equation*}


## 7.why we require Covariance matrix?

probability density function for multivariate distribution is as follows

$p(x)=\frac{1}{(2π)^{\frac{d}{2}}|Σ|^\frac{1}{2}}exp[-\frac{1}{2}(X-μ)^TΣ^{-1}(X-μ)] $

where X is input variables matrix

$μ$ is Mean matrix for each column of input

d is number of inputs

$Σ$ is covariance matrix

for multivariate normal distribution probability density function has Covariance matrix.

**For analysis and plotting of multivariate distribution Covariance matrix is required**

## 8.what is difference between covariance and correlation

<table><tbody>
<tr>
<td>
<h3><strong>Basis for comparison</strong></h3>
</td>
<td>
<h3><strong>Covariance</strong></h3>
</td>
<td>
<h3><strong>Correlation</strong></h3>
</td>
</tr>
<tr>
<td>
<p><strong>Definition</strong></p>
</td>
<td>
<p>Covariance is an indicator of the extent to which 2 random variables are dependent on each other. A higher number denotes higher dependency.</p>
</td>
<td>
<p>Correlation is a statistical measure that indicates how strongly two variables are related.</p>
</td>
</tr>
<tr>
<td>
<p><strong>Values</strong></p>
</td>
<td>
<p>The value of covariance lies in the range of -∞ and +∞.</p>
</td>
<td>
<p>Correlation is limited to values between the range -1 and +1</p>
</td>
</tr>
<tr>
<td>
<p><strong>Change in scale</strong></p>
</td>
<td>
<p>Affects covariance</p>
</td>
<td>
<p>Does not affect the correlation</p>
</td>
</tr>
<tr>
<td>
<p><strong>Unit-free measure</strong></p>
</td>
<td>
<p>No</p>
</td>
<td>
<p>Yes</p>
</td>
</tr>
</tbody></table>

## 9.What is data simplification?

### summarising large data with few variables

## 10.What is exploratory data analysis?

###  generating hypotheses about data

## 11. what is multivariate classification?

### when predicted variable is discrete

## 12.What is multivariate regression?


### when predicted variable is numeric

## 13.create matrix in python

In [ ]:
# Python code to demonstrate the
# use of numpy.cov
import numpy as np

x = [2, 8, 18, 20,28,30]

y = [5, 12, 18,23, 45,50]

# find out covariance with respect columns
cov_mat = np.stack((x, y), axis = 0)
print(cov_mat)


[[ 2  8 18 20 28 30]
 [ 5 12 18 23 45 50]]


## 14.Calculate Covariance Matrix

In [ ]:
print(np.cov(cov_mat))


[[120.66666667 189.4       ]
 [189.4        329.1       ]]


## 15.calculate Correlation coefficient

In [ ]:
corr = np.corrcoef(cov_mat)
print(corr)

[[1.        0.9504349]
 [0.9504349 1.       ]]


In [ ]:
from scipy.stats import pearsonr
# Apply the pearsonr()
corr, _ = pearsonr(x, y)
print('Pearsons correlation: %.3f' % corr)


Pearsons correlation: 0.950
